### ISSUE TITLE
Non-ASCII key names on MacOS

### ISSUE THREAD

**Issue by richardschneider** [libp2p/js-libp2p-keychain#16]
Jenkins CI is failing on macos [build](https://ci.ipfs.team/blue/organizations/jenkins/libp2p%2Fjs-libp2p-keychain/detail/automatic-ci-script-update/3/pipeline).  I suspect its an issue with `js-datastore-fs` and non-ASCII key names.
```
 Uncaught AssertionError: expected { Object (name, id) } to deeply equal { Object (name, id) }
      + expected - actual

       {
         "id": "QmYseKb5qsWa7cB5HKMEktsG6TfbYNx7yMrauNKY3mtvHx"
      -  "name": "tajné jméno"
      +  "name": "tajné jméno"
       }

at ks.findKeyById (test/keychain.spec.js:148:31)
at listKeys (src/keychain.js:246:7)
```

@diasdavid Should I write test and raise an issue?

See https://stackoverflow.com/questions/9757843/unicode-encoding-for-filesystem-in-mac-os-x-not-correct-in-python and https://github.com/nodejs/node/issues/2165

**Comment by richardschneider** [comment]
[Working with different filesystems](https://nodejs.org/en/docs/guides/working-with-different-filesystems/) describes the issue and how to deal with it. Basically it is saying to use [string.normalize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) whenever comparing file names.
